# Generated by Django 3.0.8 on 2020-07-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_question',
            name='user_question',
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='question',
            field=models.CharField(default='0000000', max_length=900),
        ),
        migrations.AlterField(
            model_name='quiz_question',
            name='choice_1',
            field=models.CharField(default='0000000', max_length=200),
        ),
        migrations.AlterField(
            model_name='quiz_question',
            name='choice_2',
            field=models.CharField(default='0000000', max_length=200),
        ),
        migrations.AlterField(
            model_name='quiz_question',
            name='choice_3',
            field=models.CharField(default='0000000', max_length=200),
        ),
        migrations.AlterField(
            model_name='quiz_question',
            name='choice_4',
            field=models.CharField(default='0000000', max_length=200),
        ),
    ]
