# Generated by Django 3.0.8 on 2020-07-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='0000000', max_length=900)),
                ('unique_id', models.IntegerField(default=0)),
            ],
        ),
    ]
