# Generated by Django 3.0.8 on 2020-08-02 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200802_0806'),
        ('crquiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_quiz',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='create_quiz',
            name='quiz_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Quiz_question'),
        ),
    ]
