# Generated by Django 3.0.8 on 2020-08-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crquiz', '0002_auto_20200802_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_quiz',
            name='quiz_question',
        ),
    ]
