# Generated by Django 3.0.8 on 2020-07-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200729_1312'),
        ('crquiz', '0003_auto_20200729_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_quiz',
            name='quizques',
        ),
        migrations.AddField(
            model_name='create_quiz',
            name='quizques',
            field=models.ManyToManyField(to='questions.Quiz_question'),
        ),
    ]
